name: research_p
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  url_launcher: ^6.2.5

  # Core dependencies
  syncfusion_flutter_pdfviewer: ^29.1.37
  path_provider: ^2.1.2
  share_plus: ^10.1.4
  http: ^1.2.0
  path: ^1.8.0
  logging: ^1.2.0
  intl: ^0.19.0  # Required by syncfusion_flutter_pdfviewer
  async: ^2.12.0  # Using SDK compatible version
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  vm_service: 14.3.1  # Keep pinned version for SDK compatibility
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/faculty/
    - assets/images/defaults/
    - assets/images/
    - assets/papers/
    - assets/images/defaults/profile.png
    - assets/images/background/welcome_bg.png
    - assets/images/logo/logo.png
    - assets/images/icons/google.png




